version: '3.9'

services:
  db:
    image: mariadb:10.5
    ports:
      - 33061:3306
    container_name: leave_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_e_leave
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=mypassword